### ISSUE TITLE
Quarto Preview for PDF

### ISSUE THREAD

**Issue by weberam2** [quarto-dev/quarto-nvim#128]
Sorry if this is obvious.

I am using the quarto kickstarter.

I can get QuartoPreview to work with html: (my _quarto.yml)

```
project:
  type: manuscript
  render: 
    - "*.qmd"
    - "!pyvenv_csvo/"

execute:
  freeze: auto

format:
  html:
    embed-resources: true
    toc: true
    comments:
      hypothesis: true
      
  # docx: default
  # jats: default
  
  # nature-pdf:
  #   journal: "sn-nature"
  #   keep-tex: true

filters:
  - parse-latex
```

But it doesn't work when I try to render to pdf:

```
project:
  type: manuscript
  render: 
    - "*.qmd"
    - "!pyvenv_csvo/"

execute:
  freeze: auto

format:
  # html:
  #   embed-resources: true
  #   toc: true
  #   comments:
  #     hypothesis: true
      
  # docx: default
  # jats: default
  
  nature-pdf:
    journal: "sn-nature"
    keep-tex: true

filters:
  - parse-latex
```

I get this error:

![image](https://github.com/quarto-dev/quarto-nvim/assets/16805029/aa84d282-cbd4-4bc0-9997-91018690e83b)

I will say, this does render when I use Rstudio... so it's not a ...conversion problem.

Cheers,

Alex W.
