### ISSUE TITLE
Autocomplete for in-text citation entries 

### ISSUE THREAD

**Issue by acebulsk** [quarto-dev/quarto-nvim#42]
Maybe this is already available but I could not find out how to enable it. Is it possible to have auto-complete work after typing the `@` symbol to search entries listed in the bibliography entered within the yaml header.

i.e.

```
I am searching for the citation @cit....
```

would autocomplete `@cit` from the bibliography below:

```
---
title: "Notes on Reading List"
format: 
  pdf:
    toc: true 
bibliography: '../papers/bibtex/library.bib'
---
```

Also it would be nice to disable spellcheck after the `@` symbol.
